version: '3.9'
services:
  r1:
    image: frrouting/frr:latest
    container_name: r1
    privileged: true
    cap_add:
    - NET_ADMIN
    volumes:
    - ./configs/r1.conf:/etc/frr/frr.conf
    - ./configs/daemons:/etc/frr/daemons
    networks:
      net_r1_r2:
        ipv4_address: 10.0.12.2
      net_r1_r3:
        ipv4_address: 10.0.13.2
  r2:
    image: frrouting/frr:latest
    container_name: r2
    privileged: true
    cap_add:
    - NET_ADMIN
    volumes:
    - ./configs/r2.conf:/etc/frr/frr.conf
    - ./configs/daemons:/etc/frr/daemons
    networks:
      net_r1_r2:
        ipv4_address: 10.0.12.3
      net_r2_r3:
        ipv4_address: 10.0.23.2
      net_r2_r4:
        ipv4_address: 10.0.24.2
  r3:
    image: frrouting/frr:latest
    container_name: r3
    privileged: true
    cap_add:
    - NET_ADMIN
    volumes:
    - ./configs/r3.conf:/etc/frr/frr.conf
    - ./configs/daemons:/etc/frr/daemons
    networks:
      net_r1_r3:
        ipv4_address: 10.0.13.3
      net_r2_r3:
        ipv4_address: 10.0.23.3
      net_r3_r5:
        ipv4_address: 10.0.35.2
  r4:
    image: frrouting/frr:latest
    container_name: r4
    privileged: true
    cap_add:
    - NET_ADMIN
    volumes:
    - ./configs/r4.conf:/etc/frr/frr.conf
    - ./configs/daemons:/etc/frr/daemons
    networks:
      net_r2_r4:
        ipv4_address: 10.0.24.3
      net_r4_r8:
        ipv4_address: 10.0.48.2
      net_r4_r6:
        ipv4_address: 10.0.46.2
  r5:
    image: frrouting/frr:latest
    container_name: r5
    privileged: true
    cap_add:
    - NET_ADMIN
    volumes:
    - ./configs/r5.conf:/etc/frr/frr.conf
    - ./configs/daemons:/etc/frr/daemons
    networks:
      net_r3_r5:
        ipv4_address: 10.0.35.3
      net_r5_r8:
        ipv4_address: 10.0.58.3
      net_r5_r7:
        ipv4_address: 10.0.57.2
  r6:
    image: frrouting/frr:latest
    container_name: r6
    privileged: true
    cap_add:
    - NET_ADMIN
    volumes:
    - ./configs/r6.conf:/etc/frr/frr.conf
    - ./configs/daemons:/etc/frr/daemons
    networks:
      net_r4_r6:
        ipv4_address: 10.0.46.3
  r7:
    image: frrouting/frr:latest
    container_name: r7
    privileged: true
    cap_add:
    - NET_ADMIN
    volumes:
    - ./configs/r7.conf:/etc/frr/frr.conf
    - ./configs/daemons:/etc/frr/daemons
    networks:
      net_r5_r7:
        ipv4_address: 10.0.57.3
  r8:
    image: frrouting/frr:latest
    container_name: r8
    privileged: true
    cap_add:
    - NET_ADMIN
    volumes:
    - ./configs/r8.conf:/etc/frr/frr.conf
    - ./configs/daemons:/etc/frr/daemons
    networks:
      net_r4_r8:
        ipv4_address: 10.0.48.3
      net_r5_r8:
        ipv4_address: 10.0.58.2
networks:
  net_r1_r2:
    driver: bridge
    ipam:
      config:
      - subnet: 10.0.12.0/24
  net_r1_r3:
    driver: bridge
    ipam:
      config:
      - subnet: 10.0.13.0/24
  net_r2_r3:
    driver: bridge
    ipam:
      config:
      - subnet: 10.0.23.0/24
  net_r2_r4:
    driver: bridge
    ipam:
      config:
      - subnet: 10.0.24.0/24
  net_r3_r5:
    driver: bridge
    ipam:
      config:
      - subnet: 10.0.35.0/24
  net_r4_r8:
    driver: bridge
    ipam:
      config:
      - subnet: 10.0.48.0/24
  net_r4_r6:
    driver: bridge
    ipam:
      config:
      - subnet: 10.0.46.0/24
  net_r5_r8:
    driver: bridge
    ipam:
      config:
      - subnet: 10.0.58.0/24
  net_r5_r7:
    driver: bridge
    ipam:
      config:
      - subnet: 10.0.57.0/24
