# Dockerfile.host
FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y iproute2 \
    iputils-ping \
    traceroute && \
    rm -rf /var/lib/apt/lists/*

# Mantém o contêiner em execução
CMD ["tail", "-f", "/dev/null"]
