graph TD
    %% Hosts
    h1[H1] --- r5
    h2[H2] --- r8

    %% Roteadores
    r1[R1]
    r2[R2]
    r3[R3]
    r4[R4]
    r5[R5]
    r6[R6]
    r7[R7]
    r8[R8]

    %% Conexões entre roteadores
    r1 --- r2
    r1 --- r3
    r2 --- r4
    r2 --- r5
    r3 --- r4
    r3 --- r6
    r4 --- r7
    r6 --- r8
    r7 --- r8
